export type CuratedSource = {
  name: string;
  publisher: string;
  url: string;
  kind: "open-course" | "open-textbook" | "official" | "research";
};

export const curatedSources = {
  unescoOer: { name: "Open Educational Resources", publisher: "UNESCO", url: "https://www.unesco.org/en/open-educational-resources?hub=802", kind: "official" },
  mitCalculus: { name: "Single Variable Calculus", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/", kind: "open-course" },
  openstaxCalculus: { name: "Calculus Volume 1", publisher: "OpenStax", url: "https://openstax.org/books/calculus-volume-1/pages/preface", kind: "open-textbook" },
  mitDifferential: { name: "Differential Equations", publisher: "MIT OpenCourseWare", url: "https://www.ocw.mit.edu/courses/18-03-differential-equations-spring-2010/pages/syllabus/", kind: "open-course" },
  mitMathCs: { name: "Mathematics for Computer Science", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/6-1200j-mathematics-for-computer-science-spring-2024/", kind: "open-course" },
  mitLinearAlgebra: { name: "Linear Algebra", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/", kind: "open-course" },
  mitMechanics: { name: "Classical Mechanics", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/pages/online-textbook/", kind: "open-course" },
  mitStatics: { name: "Mechanics & Materials I", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/pages/lecture-notes/", kind: "open-course" },
  mitCircuits: { name: "Circuits and Electronics", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/video_galleries/video-lectures/", kind: "open-course" },
  cs50: { name: "CS50x 2026", publisher: "Harvard University", url: "https://cs50.harvard.edu/x/", kind: "open-course" },
  mitAlgorithms: { name: "Introduction to Algorithms", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/pages/lecture-notes/", kind: "open-course" },
  openstaxEconomics: { name: "Principles of Economics 3e", publisher: "OpenStax", url: "https://openstax.org/details/books/principles-economics-3e/", kind: "open-textbook" },
  openstaxAccounting: { name: "Principles of Financial Accounting", publisher: "OpenStax", url: "https://openstax.org/books/principles-financial-accounting/pages/1-1-explain-the-importance-of-accounting-and-distinguish-between-financial-and-managerial-accounting", kind: "open-textbook" },
  openstaxControls: { name: "Internal Controls", publisher: "OpenStax", url: "https://openstax.org/books/principles-financial-accounting/pages/8-3-describe-internal-controls-within-an-organization", kind: "open-textbook" },
  openstaxManagement: { name: "Principles of Management", publisher: "OpenStax", url: "https://openstax.org/books/principles-management/pages/preface", kind: "open-textbook" },
  openstaxPlanning: { name: "The Planning Process", publisher: "OpenStax", url: "https://openstax.org/books/principles-management/pages/17-2-the-planning-process", kind: "open-textbook" },
  openstaxMarketing: { name: "Principles of Marketing", publisher: "OpenStax", url: "https://openstax.org/books/principles-marketing/pages/preface", kind: "open-textbook" },
  openstaxPositioning: { name: "Product Positioning", publisher: "OpenStax", url: "https://openstax.org/books/principles-marketing/pages/5-6-product-positioning", kind: "open-textbook" },
  mitLogistics: { name: "Logistics Systems", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/esd-260j-logistics-systems-fall-2006/pages/lecture-notes/", kind: "open-course" },
  mitSupply: { name: "D-Lab: Supply Chains", publisher: "MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/15-772j-d-lab-supply-chains-fall-2014/resources/lecture-notes/", kind: "open-course" },
  wtoTrade: { name: "International Trading System", publisher: "World Trade Organization", url: "https://www.wto.org/english/tratop_e/devel_e/train_e/wtochairs_e/ba_jordan.pdf", kind: "official" },
  constitution: { name: "Türkiye Cumhuriyeti Anayasası", publisher: "Anayasa Mahkemesi", url: "https://www.anayasa.gov.tr/media/9862/temel-metinler-duzeltme-2025.pdf", kind: "official" },
  civilCode: { name: "Türk Medeni Kanunu", publisher: "Mevzuat Bilgi Sistemi", url: "https://www.mevzuat.gov.tr/MevzuatMetin/1.5.4721.pdf", kind: "official" },
  obligationsCode: { name: "Türk Borçlar Kanunu", publisher: "Mevzuat Bilgi Sistemi", url: "https://www.mevzuat.gov.tr/MevzuatMetin/1.5.6098.pdf", kind: "official" },
  justiceDictionary: { name: "Hukuk Sözlüğü", publisher: "T.C. Adalet Bakanlığı", url: "https://sozluk.adalet.gov.tr/", kind: "official" },
  ankaraPolitics: { name: "Siyaset Bilimi Ders İzlencesi", publisher: "Ankara Üniversitesi Açık Ders", url: "https://acikders.ankara.edu.tr/pluginfile.php/119325/mod_resource/content/0/Ders_%C4%B0zlencesi%20Siyaset%20Bilimi.pdf", kind: "open-course" },
  tbmmHistory: { name: "Cumhuriyet Dönemi: Partiler, Seçimler, Beyannameler", publisher: "TBMM", url: "https://cdn.tbmm.gov.tr/TbmmWeb/Yayinlar/Dosya/ed1d2982-f225-4467-a4ab-707f4cc471dc.pdf", kind: "official" },
  ankaraRoman: { name: "HKZ102 Roma Hukuku", publisher: "Ankara Üniversitesi Açık Ders", url: "https://acikders.ankara.edu.tr/course/view.php?id=9578", kind: "open-course" },
  romaTreRoman: { name: "Institutions of Roman Law", publisher: "Roma Tre University", url: "https://www.uniroma3.it/en/insegnamento-erogato/dipartimento-di-giurisprudenza/lm/2023-2024/law-0580707051400001/09c0fc6a-8668-4861-9d9d-26d2c00f5e1a--20110347/", kind: "open-course" },
  openstaxPsychology: { name: "Psychology 2e", publisher: "OpenStax", url: "https://openstax.org/books/psychology-2e/pages/preface", kind: "open-textbook" },
  openstaxMemory: { name: "Ways to Enhance Memory", publisher: "OpenStax", url: "https://openstax.org/books/psychology-2e/pages/8-4-ways-to-enhance-memory", kind: "open-textbook" },
  openstaxLifespan: { name: "Lifespan Development", publisher: "OpenStax", url: "https://openstax.org/books/lifespan-development/pages/preface", kind: "open-textbook" },
  apaRetrieval: { name: "Retrieval Practice Consistently Benefits Student Learning", publisher: "American Psychological Association", url: "https://www.apa.org/pubs/journals/features/edu-edu0000486.pdf", kind: "research" },
  ankaraPdr: { name: "PDR'ye Giriş Ders İzlencesi", publisher: "Ankara Üniversitesi Açık Ders", url: "https://acikders.ankara.edu.tr/pluginfile.php/208742/mod_resource/content/0/PDRye%20giri%C5%9F%20ders%20izlencesi%202022%20-%202023.pdf", kind: "open-course" },
  tdkSpelling: { name: "Yazım Kılavuzu", publisher: "Türk Dil Kurumu", url: "https://yazim.tdk.gov.tr/index.html", kind: "official" },
  tdkPunctuation: { name: "Noktalama İşaretleri", publisher: "Türk Dil Kurumu", url: "https://tdk.gov.tr/icerik/yazim-kurallari/noktalama-ve-diger-isaretler/", kind: "official" },
  ankaraGrammar: { name: "Türk Dili Bilgisi", publisher: "Ankara Üniversitesi Açık Ders", url: "https://acikders.ankara.edu.tr/course/view.php?id=10860", kind: "open-course" },
  ankaraChildren: { name: "Çocuk Edebiyatı", publisher: "Ankara Üniversitesi Açık Ders", url: "https://acikders.ankara.edu.tr/course/view.php?id=4807&lang=tr", kind: "open-course" },
  ankaraStoryAnalysis: { name: "Hikâye Tahlilleri", publisher: "Ankara Üniversitesi Açık Ders", url: "https://acikders.ankara.edu.tr/course/view.php?id=5569", kind: "open-course" },
  openstaxBiology: { name: "Biology 2e", publisher: "OpenStax", url: "https://openstax.org/details/books/biology-2e/", kind: "open-textbook" },
  openstaxCells: { name: "Studying Cells", publisher: "OpenStax", url: "https://openstax.org/books/biology-2e/pages/4-1-studying-cells", kind: "open-textbook" },
  openstaxAnatomy: { name: "Anatomy and Physiology 2e", publisher: "OpenStax", url: "https://openstax.org/books/anatomy-and-physiology-2e/pages/preface", kind: "open-textbook" },
  openstaxActionPotential: { name: "The Action Potential", publisher: "OpenStax", url: "https://openstax.org/books/anatomy-and-physiology-2e/pages/12-4-the-action-potential", kind: "open-textbook" },
  openstaxEndocrine: { name: "Overview of the Endocrine System", publisher: "OpenStax", url: "https://openstax.org/books/anatomy-and-physiology-2e/pages/17-1-an-overview-of-the-endocrine-system", kind: "open-textbook" },
  ncbiHomeostasis: { name: "Physiology, Homeostasis", publisher: "NCBI Bookshelf / NIH", url: "https://www.ncbi.nlm.nih.gov/books/NBK559138/", kind: "research" },
  ncbiInflammation: { name: "Pathology, Inflammation", publisher: "NCBI Bookshelf / NIH", url: "https://www.ncbi.nlm.nih.gov/books/NBK534820/", kind: "research" },
  openstaxChemistry: { name: "Chemistry 2e", publisher: "OpenStax", url: "https://openstax.org/books/chemistry-2e/pages/4-summary", kind: "open-textbook" },
} as const satisfies Record<string, CuratedSource>;

export type CuratedSourceKey = keyof typeof curatedSources;

export type CuratedNote = {
  id: string;
  courseCodes: string[];
  category: string;
  title: string;
  summary: string;
  takeaways: string[];
  checklist: string[];
  tags: string[];
  sourceKeys: CuratedSourceKey[];
  readingMinutes: number;
  level: "Başlangıç" | "Orta";
  featured?: boolean;
  verifiedOn: string;
};

const verifiedOn = "2026-09-03";

function note(input: Omit<CuratedNote, "verifiedOn">): CuratedNote {
  return { ...input, verifiedOn };
}

export const curatedNotes: CuratedNote[] = [
  note({ id: "limit-sureklilik", courseCodes: ["MAT 101", "İMA 101"], category: "Matematik", title: "Limit ve süreklilik: çözüm karar ağacı", summary: "Bir limit sorusunda doğrudan yerine koyma, cebirsel sadeleştirme ve tek taraflı limit adımlarını hangi sırayla deneyeceğini özetler.", takeaways: ["Önce tanım kümesini ve yaklaşım yönünü belirle.", "0/0 belirsizliği sonuç değil, dönüşüm gerektiğinin işaretidir.", "Süreklilik için değer, limit ve eşitlik koşullarının üçü de gerekir."], checklist: ["Parçalı fonksiyonlarda sağ ve sol limiti ayrı yaz.", "Payda sıfır oluyorsa çarpanlara ayırmayı dene.", "Sonucu grafik davranışıyla kontrol et."], tags: ["limit", "süreklilik", "analiz"], sourceKeys: ["mitCalculus", "openstaxCalculus"], readingMinutes: 7, level: "Başlangıç", featured: true }),
  note({ id: "turev-kurallari", courseCodes: ["MAT 101", "İMA 101"], category: "Matematik", title: "Türev kuralları ve anlamı", summary: "Türevi yalnızca formül değil, anlık değişim hızı ve teğet eğimi olarak kullanmak için kısa bir çalışma notu.", takeaways: ["Türev yerel doğrusal yaklaşımı verir.", "Çarpım, bölüm ve zincir kuralları farklı bileşim yapılarını çözer.", "Kritik nokta türevin sıfır ya da tanımsız olduğu aday noktadır."], checklist: ["İşleme başlamadan dış ve iç fonksiyonu işaretle.", "Birimleri türev sonucuna taşı.", "Ekstremum adaylarını işaret tablosuyla doğrula."], tags: ["türev", "zincir kuralı", "optimizasyon"], sourceKeys: ["mitCalculus", "openstaxCalculus"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "integral-ftc", courseCodes: ["MAT 101", "İMA 101"], category: "Matematik", title: "Belirli integral ve Analizin Temel Teoremi", summary: "Toplam, alan ve birikim fikirlerini türevle bağlayan temel çerçeve.", takeaways: ["Belirli integral net birikimi ölçer; her zaman geometrik alan değildir.", "Temel teorem türev ve integrali ters süreçler olarak bağlar.", "Değişken dönüşümü diferansiyel ve sınırlarla birlikte uygulanır."], checklist: ["İntegrandın işaretini aralıkta incele.", "Belirli integralde sabit ekleme.", "Değişken dönüşümünde sınırları da dönüştür."], tags: ["integral", "temel teorem", "alan"], sourceKeys: ["mitCalculus", "openstaxCalculus"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "diziler-seriler", courseCodes: ["MAT 101", "İMA 201"], category: "Matematik", title: "Dizi ve seri yakınsaklığı", summary: "Terim limiti ile seri toplamını ayırır; geometrik seri ve temel yakınsaklık testlerini konumlandırır.", takeaways: ["Bir dizinin yakınsaklığı terimlerin limitidir.", "Bir serinin yakınsaklığı kısmi toplamlar dizisinin limitidir.", "Seri yakınsaksa terimleri sıfıra gider; tersi tek başına doğru değildir."], checklist: ["Önce genel terim sıfıra gidiyor mu kontrol et.", "Geometrik ya da teleskopik yapıyı ara.", "Test koşullarını uygulamadan önce yaz."], tags: ["dizi", "seri", "yakınsaklık"], sourceKeys: ["openstaxCalculus", "mitCalculus"], readingMinutes: 9, level: "Orta" }),
  note({ id: "matris-gauss", courseCodes: ["MAT 101", "İMA 201"], category: "Matematik", title: "Matrisler ve Gauss elemesi", summary: "Doğrusal denklem sistemini artırılmış matrisle çözerken satır işlemlerinin neyi koruduğunu açıklar.", takeaways: ["Temel satır işlemleri eşdeğer denklem sistemi üretir.", "Pivot sayısı matrisin rütbesini gösterir.", "Serbest değişken varsa çözüm parametrik ifade edilir."], checklist: ["Artırılmış matrisi doğru sırayla kur.", "Her pivotun altını sıfırla.", "Tutarsız satır ve serbest değişken kontrolü yap."], tags: ["matris", "gauss", "doğrusal sistem"], sourceKeys: ["mitLinearAlgebra"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "ispat-tumevarim", courseCodes: ["İMA 201", "BİL 203"], category: "Matematik", title: "İspat kurma: doğrudan, çelişki ve tümevarım", summary: "Bir önermeye uygun ispat stratejisini seçmek ve eksik mantık halkalarını görmek için şablon.", takeaways: ["Doğrudan ispat varsayımdan hedefe geçerli çıkarımlar kurar.", "Çelişki ispatı hedefin değillemesini varsayar.", "Tümevarımda başlangıç ve geçiş adımları ayrı zorunluluklardır."], checklist: ["Nicelikleri ve varsayımları açıkça yaz.", "Kullanılan teoremin koşullarını doğrula.", "Tümevarım varsayımını yalnız izin verilen yerde kullan."], tags: ["ispat", "tümevarım", "mantık"], sourceKeys: ["mitMathCs"], readingMinutes: 9, level: "Orta" }),
  note({ id: "birinci-derece-ode", courseCodes: ["MAT 101"], category: "Matematik", title: "Birinci derece diferansiyel denklemler", summary: "Ayrılabilir ve doğrusal birinci derece denklemleri tanıma, çözme ve başlangıç koşulunu uygulama rehberi.", takeaways: ["Denklemin türünü işlemden önce sınıflandır.", "Doğrusal formda integrasyon çarpanı katsayıdan türetilir.", "Başlangıç koşulu genel çözümdeki sabiti belirler."], checklist: ["Çözümü özgün denkleme geri koy.", "Değişken ayırırken kaybolabilecek sabit çözümleri kontrol et.", "Başlangıç koşulunun tanım aralığını incele."], tags: ["diferansiyel denklem", "integrasyon çarpanı", "başlangıç değeri"], sourceKeys: ["mitDifferential"], readingMinutes: 10, level: "Orta" }),
  note({ id: "ikinci-derece-ode", courseCodes: ["MAT 101"], category: "Matematik", title: "İkinci derece sabit katsayılı denklemler", summary: "Karakteristik köklerin gerçek, tekrarlı veya karmaşık oluşuna göre homojen çözüm biçimlerini karşılaştırır.", takeaways: ["Karakteristik polinom çözüm ailesini belirler.", "Tekrarlı kökte bağımsız ikinci çözüm bir t çarpanı taşır.", "Karmaşık kökler gerçek sinüs-kosinüs biçiminde yazılabilir."], checklist: ["Homojen ve özel çözümü ayır.", "Başlangıç koşullarını son genel çözüme uygula.", "Türevleri yerine koyarak doğrula."], tags: ["diferansiyel denklem", "karakteristik kök", "laplace"], sourceKeys: ["mitDifferential"], readingMinutes: 10, level: "Orta" }),
  note({ id: "algoritmik-dusunme", courseCodes: ["BİL 101"], category: "Bilgisayar Bilimleri", title: "Algoritmik düşünme ve sözde kod", summary: "Problemi girdi, çıktı, kısıt ve küçük doğrulanabilir adımlara ayıran başlangıç rehberi.", takeaways: ["Koddan önce beklenen girdiyi ve çıktıyı kesinleştir.", "Bir algoritma sonlu ve belirsiz olmayan adımlardan oluşur.", "Sınır durumları normal akış kadar tasarımın parçasıdır."], checklist: ["En küçük örneği elle çöz.", "Döngü değişmezini bir cümleyle yaz.", "Boş, tek elemanlı ve hatalı girdiyi dene."], tags: ["algoritma", "sözde kod", "problem çözme"], sourceKeys: ["cs50"], readingMinutes: 7, level: "Başlangıç", featured: true }),
  note({ id: "c-bellek", courseCodes: ["BİL 101"], category: "Bilgisayar Bilimleri", title: "C'de bellek, işaretçi ve dizi ilişkisi", summary: "Değer, adres, işaretçi ve dizi kavramlarını aynı bellek modeli üzerinde birbirinden ayırır.", takeaways: ["İşaretçi bir bellek adresini tutan değişkendir.", "Dizi erişiminde sınır denetimi programcının sorumluluğundadır.", "Dinamik ayrılan bellek yaşam döngüsü sonunda serbest bırakılmalıdır."], checklist: ["Tür ve işaretçi seviyesini çizerek takip et.", "NULL ve dizi sınırı kontrolleri ekle.", "Her ayırma için sahipliği ve serbest bırakmayı belirle."], tags: ["c", "bellek", "işaretçi"], sourceKeys: ["cs50"], readingMinutes: 9, level: "Orta" }),
  note({ id: "veri-yapisi-secimi", courseCodes: ["BİL 203"], category: "Bilgisayar Bilimleri", title: "Veri yapısı seçimi: işlem maliyetine göre", summary: "Dizi, bağlı liste, yığın, kuyruk ve karma tablonun güçlü olduğu işlemleri karşılaştırır.", takeaways: ["En iyi yapı, baskın işlemlere göre seçilir.", "Asimptotik maliyet yanında bellek ve erişim düzeni de önemlidir.", "Yığın LIFO, kuyruk FIFO düzenini uygular."], checklist: ["Arama, ekleme ve silme sıklığını yaz.", "En kötü durum maliyetini belirt.", "Bellek ek yükünü ve sıralama gereksinimini değerlendir."], tags: ["veri yapıları", "yığın", "kuyruk"], sourceKeys: ["mitAlgorithms", "cs50"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "asimptotik-analiz", courseCodes: ["BİL 203", "İMA 201"], category: "Bilgisayar Bilimleri", title: "Big-O ile büyüme analizi", summary: "Girdi büyüdüğünde zaman ve alan gereksiniminin baskın davranışını karşılaştırma notu.", takeaways: ["Big-O bir üst büyüme sınırını ifade eder.", "Sabitler ve düşük dereceli terimler asimptotik sınıfta elenir.", "Aynı sınıftaki iki uygulama pratikte yine farklı performans gösterebilir."], checklist: ["Girdinin neyi temsil ettiğini tanımla.", "Ardışık maliyetleri topla, iç içe maliyetleri çarp.", "En kötü, ortalama ve amorti edilmiş durumu karıştırma."], tags: ["big o", "karmaşıklık", "performans"], sourceKeys: ["mitAlgorithms", "mitMathCs"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "siralamalar", courseCodes: ["BİL 203"], category: "Bilgisayar Bilimleri", title: "Sıralama algoritmaları karşılaştırması", summary: "Ekleme, birleştirme ve hızlı sıralamayı süre, alan, kararlılık ve girdi yapısı açısından kıyaslar.", takeaways: ["Birleştirme sıralaması öngörülebilir O(n log n) süre sunar.", "Ekleme sıralaması küçük veya neredeyse sıralı girdide kullanışlıdır.", "Hızlı sıralamanın performansı pivot seçimine bağlıdır."], checklist: ["Kararlılık gerekip gerekmediğini belirle.", "Yerinde çalışma ve ek bellek koşulunu yaz.", "En kötü durum davranışını ayrıca kontrol et."], tags: ["sıralama", "merge sort", "quick sort"], sourceKeys: ["mitAlgorithms"], readingMinutes: 9, level: "Orta" }),
  note({ id: "hash-bst", courseCodes: ["BİL 203"], category: "Bilgisayar Bilimleri", title: "Karma tablo ve ikili arama ağacı", summary: "Anahtarla erişim için karma tablo ile sıralı yapı gereken durumlarda dengeli arama ağacını konumlandırır.", takeaways: ["Karma tabloda beklenen erişim sabit olabilir, çakışma yine yönetilmelidir.", "Dengeli BST sıralı gezinme ve logaritmik işlemler sağlar.", "Kötü hash dağılımı performansı ciddi biçimde düşürür."], checklist: ["Anahtar eşitliği ve hash sözleşmesini belirle.", "Yük faktörünü izle.", "Sıralı aralık sorgusu gereksinimini kontrol et."], tags: ["hash", "ağaç", "arama"], sourceKeys: ["mitAlgorithms", "cs50"], readingMinutes: 9, level: "Orta" }),
  note({ id: "graf-gezinme", courseCodes: ["BİL 203", "İMA 201"], category: "Bilgisayar Bilimleri", title: "Graf gezme: BFS, DFS ve kısa yollar", summary: "Grafı temsil etme, ziyaret durumunu izleme ve probleme uygun gezinme yöntemini seçme rehberi.", takeaways: ["BFS ağırlıksız grafikte kenar sayısı bakımından en kısa yolları bulur.", "DFS bileşen, çevrim ve topolojik yapı incelemelerinde kullanışlıdır.", "Ziyaret kümesi tekrar işlemeyi ve sonsuz döngüyü önler."], checklist: ["Yönlü/yönsüz ve ağırlıklı/ağırlıksız ayrımını yap.", "Komşuluk listesi ya da matrisi seçimini gerekçelendir.", "Bağlantısız bileşenler için tüm düğümleri tara."], tags: ["graf", "bfs", "dfs"], sourceKeys: ["mitAlgorithms", "mitMathCs"], readingMinutes: 10, level: "Orta" }),
  note({ id: "dinamik-programlama", courseCodes: ["BİL 203"], category: "Bilgisayar Bilimleri", title: "Dinamik programlama: durumdan çözüme", summary: "Örtüşen alt problemleri ve optimal alt yapıyı tanıyıp yineleme bağıntısı kurma şablonu.", takeaways: ["Durum, gelecekteki kararı etkileyen yeterli bilgiyi taşır.", "Geçiş, daha küçük durumların sonuçlarını birleştirir.", "Memoization üstten alta, tabulation alttan üste hesaplar."], checklist: ["Durumun anlamını tek cümleyle tanımla.", "Başlangıç durumlarını açıkça yaz.", "Hesaplama sırasının bağımlılıkları karşıladığını doğrula."], tags: ["dinamik programlama", "özyineleme", "optimizasyon"], sourceKeys: ["mitAlgorithms"], readingMinutes: 10, level: "Orta" }),
  note({ id: "vektor-kinematik", courseCodes: ["FİZ 101", "MAK 101"], category: "Fizik ve Mühendislik", title: "Vektörler ve kinematik", summary: "Konum, hız ve ivmeyi vektör bileşenleriyle okuyup hareket denklemlerini doğru koşulda kullanma notu.", takeaways: ["Hız konumun, ivme hızın zamana göre türevidir.", "Sabit ivme denklemleri yalnız ivme sabitken geçerlidir.", "İki boyutlu hareket bağımsız eksen bileşenlerine ayrılabilir."], checklist: ["Koordinat sistemini ve pozitif yönü çiz.", "Verilenleri birimleriyle yaz.", "Sonucun yönünü ve boyutunu kontrol et."], tags: ["kinematik", "vektör", "ivme"], sourceKeys: ["mitMechanics"], readingMinutes: 8, level: "Başlangıç", featured: true }),
  note({ id: "newton-serbest-cisim", courseCodes: ["FİZ 101", "MAK 101"], category: "Fizik ve Mühendislik", title: "Newton yasaları ve serbest cisim diyagramı", summary: "Kuvvetleri doğru cisme yerleştirip net kuvvet denklemlerini eksen bazında kurma rehberi.", takeaways: ["Serbest cisim diyagramında yalnız seçilen cisme etki eden kuvvetler bulunur.", "Net kuvvet sıfırsa hızın sıfır olması gerekmez.", "Etki-tepki kuvvetleri farklı cisimler üzerindedir."], checklist: ["İncelenen sistemi sınırla.", "Her kuvvetin kaynağını adlandır.", "Denklemleri seçilen eksenlerde bileşenlere ayır."], tags: ["newton", "kuvvet", "serbest cisim"], sourceKeys: ["mitMechanics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "is-enerji", courseCodes: ["FİZ 101"], category: "Fizik ve Mühendislik", title: "İş, enerji ve güç", summary: "Kuvvet yaklaşımı yerine enerji yaklaşımının ne zaman daha kısa olduğunu gösteren kavram özeti.", takeaways: ["Net iş kinetik enerjideki değişime eşittir.", "Korunumlu kuvvetler için potansiyel enerji tanımlanabilir.", "Güç, iş yapma hızıdır ve anlık olarak kuvvet-hız skaler çarpımıdır."], checklist: ["Başlangıç ve son durumu açıkça seç.", "Sürtünme gibi korunumsuz işleri ayrı yaz.", "Referans potansiyel seviyesini belirt."], tags: ["enerji", "iş", "güç"], sourceKeys: ["mitMechanics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "momentum-carpisma", courseCodes: ["FİZ 101"], category: "Fizik ve Mühendislik", title: "Momentum, itme ve çarpışmalar", summary: "Sistem seçimi ve dış itme üzerinden momentum korunumunu elastik ve elastik olmayan çarpışmalara uygular.", takeaways: ["İtme momentum değişimine eşittir.", "Toplam momentum, net dış itme ihmal edilebiliyorsa korunur.", "Kinetik enerji yalnız elastik çarpışmada korunur."], checklist: ["Sisteme dahil cisimleri yaz.", "Çarpışma öncesi ve sonrası yön işaretlerini koru.", "Enerji korunumu varsayımını ayrıca gerekçelendir."], tags: ["momentum", "itme", "çarpışma"], sourceKeys: ["mitMechanics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "donme-tork", courseCodes: ["FİZ 101", "MAK 203"], category: "Fizik ve Mühendislik", title: "Dönme hareketi, tork ve açısal momentum", summary: "Doğrusal hareket büyüklüklerinin dönme hareketindeki karşılıklarını ve eksen seçiminin etkisini toplar.", takeaways: ["Tork kuvvetin dönme etkisidir ve eksene bağlıdır.", "Sabit eksende net tork açısal ivmeyle ilişkilidir.", "Dış tork sıfırsa açısal momentum korunur."], checklist: ["Dönme eksenini belirt.", "Moment kolunu dik uzaklık olarak kullan.", "Saat yönü işaret kuralını tutarlı uygula."], tags: ["tork", "dönme", "açısal momentum"], sourceKeys: ["mitMechanics", "mitStatics"], readingMinutes: 9, level: "Orta" }),
  note({ id: "statik-denge", courseCodes: ["MAK 203"], category: "Fizik ve Mühendislik", title: "Statik denge: kuvvet ve moment denklemleri", summary: "Rijit cismin iki boyutlu denge problemlerinde mesnet tepkilerini sistematik çözme şablonu.", takeaways: ["Denge için kuvvetlerin ve momentlerin toplamı sıfırdır.", "Moment noktası bilinmeyenleri azaltacak biçimde seçilebilir.", "Mesnet türü üretebileceği tepki bileşenlerini belirler."], checklist: ["Cismi çevresinden ayırıp tüm tepkileri göster.", "Dağıtılmış yükü eşdeğer tekil yüke dönüştür.", "Çözüm sonunda tüm denge denklemlerini kontrol et."], tags: ["statik", "denge", "moment"], sourceKeys: ["mitStatics"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "kafes-surtunme", courseCodes: ["MAK 203"], category: "Fizik ve Mühendislik", title: "Kafes sistemleri ve kuru sürtünme", summary: "Düğüm/ kesit yöntemlerini ve Coulomb sürtünme modelini tek çalışma çerçevesinde toplar.", takeaways: ["İdeal kafes çubukları yalnız eksenel çekme veya basınç taşır.", "Düğüm yöntemi her düğümün dengesini kullanır.", "Statik sürtünme her zaman sınır değerinde değildir; gereken değere kadar uyum sağlar."], checklist: ["Sıfır kuvvetli çubuk adaylarını belirle.", "Çekme varsayımıyla başlayıp işareti yorumla.", "Kayma eşiği yoksa sürtünmeyi doğrudan μN alma."], tags: ["kafes", "sürtünme", "çubuk"], sourceKeys: ["mitStatics"], readingMinutes: 10, level: "Orta" }),
  note({ id: "kcl-kvl", courseCodes: ["EEM 101", "EEM 203"], category: "Fizik ve Mühendislik", title: "Devre analizinin omurgası: Ohm, KCL ve KVL", summary: "Düğüm gerilimleri ve çevre akımlarıyla dirençli devreleri çözmek için temel denklemleri konumlandırır.", takeaways: ["Ohm yasası eleman gerilim-akım ilişkisini verir.", "KCL düğümde yük birikmediği varsayımıyla akımları dengeler.", "KVL kapalı çevrede gerilim değişimlerinin toplamını sıfırlar."], checklist: ["Akım yönlerini ve gerilim polaritelerini başta seç.", "Bağımsız denklem sayısını kontrol et.", "Güç toplamıyla çözümü doğrula."], tags: ["ohm", "kcl", "kvl"], sourceKeys: ["mitCircuits"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "thevenin-norton", courseCodes: ["EEM 203"], category: "Fizik ve Mühendislik", title: "Thevenin ve Norton eşdeğerleri", summary: "Karmaşık doğrusal iki uçlu ağı yük açısından tek kaynak ve dirençle temsil etme rehberi.", takeaways: ["Thevenin gerilimi açık devre uç gerilimidir.", "Norton akımı kısa devre akımıdır.", "Kaynak dönüşümünde eşdeğer direnç aynı kalır."], checklist: ["Yükü devreden ayır.", "Bağımsız kaynakları etkisizleştirirken türüne dikkat et.", "Bağımlı kaynak varsa test kaynağı kullan."], tags: ["thevenin", "norton", "eşdeğer devre"], sourceKeys: ["mitCircuits"], readingMinutes: 9, level: "Orta" }),
  note({ id: "rc-gecici", courseCodes: ["EEM 203"], category: "Fizik ve Mühendislik", title: "RC devrelerinde geçici rejim", summary: "Kondansatör geriliminin sürekliliği, zaman sabiti ve başlangıç/son değerlerle çözümü hızlandırır.", takeaways: ["İdeal kondansatör gerilimi ani değişemez.", "Birinci derece RC yanıtı başlangıçtan son değere üstel yaklaşır.", "Zaman sabiti devrenin değişim hızını belirler."], checklist: ["Anahtarlama öncesi kararlı durumu bul.", "t=0+ ve t→∞ değerlerini yaz.", "Kondansatörün gördüğü eşdeğer direnci hesapla."], tags: ["rc", "kondansatör", "geçici rejim"], sourceKeys: ["mitCircuits"], readingMinutes: 9, level: "Orta" }),
  note({ id: "kitlik-firsat-maliyeti", courseCodes: ["İKT 101"], category: "İktisat", title: "Kıtlık, tercih ve fırsat maliyeti", summary: "İktisadi kararların neden vazgeçilen en iyi alternatif üzerinden değerlendirildiğini açıklar.", takeaways: ["Kıtlık, sınırlı kaynaklarla sınırsız istekler arasındaki gerilimdir.", "Fırsat maliyeti vazgeçilen en değerli alternatiftir.", "Batık maliyet gelecekteki rasyonel kararı belirlememelidir."], checklist: ["Karar alternatiflerini açıkça listele.", "Parasal olmayan maliyetleri dahil et.", "Marjinal fayda ile marjinal maliyeti karşılaştır."], tags: ["kıtlık", "fırsat maliyeti", "marjinal analiz"], sourceKeys: ["openstaxEconomics"], readingMinutes: 7, level: "Başlangıç" }),
  note({ id: "arz-talep", courseCodes: ["İKT 101", "İKT 201"], category: "İktisat", title: "Arz-talep dengesi ve kaymalar", summary: "Eğri üzerinde hareket ile eğrinin kaymasını ayırıp yeni dengeyi adım adım analiz eder.", takeaways: ["Fiyat değişimi aynı eğri üzerinde hareket yaratır.", "Fiyat dışı belirleyiciler eğriyi kaydırır.", "Denge fiyatı arz edilen ve talep edilen miktarı eşitler."], checklist: ["Hangi piyasanın incelendiğini tanımla.", "Önce hangi eğrinin hangi yöne kaydığını belirle.", "Fiyat ve miktar etkisini ayrı sonuçlandır."], tags: ["arz", "talep", "denge"], sourceKeys: ["openstaxEconomics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "esneklik", courseCodes: ["İKT 101", "İKT 201", "PAZ 201"], category: "İktisat", title: "Esneklik: oranları doğru yorumlama", summary: "Talep ve arzın fiyat ya da gelir değişimine duyarlılığını yüzde değişimler üzerinden okur.", takeaways: ["Fiyat esnekliği birimden bağımsız bir duyarlılık ölçüsüdür.", "Talep esnek olduğunda fiyat ve toplam gelir ters yönde hareket eder.", "Esneklik eğimin aynısı değildir ve eğri boyunca değişebilir."], checklist: ["Hangi esnekliğin istendiğini belirle.", "Yüzde değişim tabanını tutarlı kullan.", "İşaretten çok mutlak değer kategorisini yorumla."], tags: ["esneklik", "talep", "toplam gelir"], sourceKeys: ["openstaxEconomics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "tuketici-uretici", courseCodes: ["İKT 201"], category: "İktisat", title: "Tüketici ve üretici kararlarında marjinal düşünme", summary: "Bütçe kısıtı, fayda, maliyet ve kâr maksimizasyonunu ortak marjinal karar mantığında birleştirir.", takeaways: ["Tüketici bütçe altında tercih yapar.", "Firma kârı toplam gelir ile toplam maliyet farkıdır.", "İç çözümde karar bir birim daha artırmanın fayda ve maliyetini karşılaştırır."], checklist: ["Kısıtı ve amaç fonksiyonunu ayır.", "Sabit ve değişken maliyeti karıştırma.", "Köşe çözümleri ayrıca kontrol et."], tags: ["mikroiktisat", "marjinal fayda", "maliyet"], sourceKeys: ["openstaxEconomics"], readingMinutes: 9, level: "Orta" }),
  note({ id: "piyasa-yapilari", courseCodes: ["İKT 201"], category: "İktisat", title: "Piyasa yapıları karşılaştırma tablosu", summary: "Tam rekabet, tekel, tekelci rekabet ve oligopolü giriş engeli, ürün ve fiyatlama açısından karşılaştırır.", takeaways: ["Piyasa gücü firmanın fiyatı etkileme kapasitesidir.", "Tam rekabette firma piyasa fiyatını veri alır.", "Oligopolde her firmanın kararı rakiplerin tepkisine bağlıdır."], checklist: ["Firma sayısını tek ölçüt olarak kullanma.", "Giriş engeli ve ürün farklılaşmasını yaz.", "Kısa ve uzun dönem sonuçlarını ayır."], tags: ["piyasa yapıları", "tekel", "rekabet"], sourceKeys: ["openstaxEconomics"], readingMinutes: 9, level: "Orta" }),
  note({ id: "makro-gostergeler", courseCodes: ["İKT 202"], category: "İktisat", title: "GSYH, enflasyon ve işsizlik", summary: "Üç temel makro göstergenin neyi ölçtüğünü, neyi ölçmediğini ve nominal-reel ayrımını açıklar.", takeaways: ["GSYH belirli dönemde üretilen nihai mal ve hizmetlerin piyasa değeridir.", "Reel büyüklükler fiyat düzeyi etkisinden arındırılır.", "İşsizlik oranı işgücü içindeki işsizlerin payıdır."], checklist: ["Stok ve akım değişkenlerini ayır.", "Nominal değeri uygun fiyat endeksiyle düzelt.", "Oranın paydasını açıkça yaz."], tags: ["gsyh", "enflasyon", "işsizlik"], sourceKeys: ["openstaxEconomics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "maliye-para-politikasi", courseCodes: ["İKT 202"], category: "İktisat", title: "Maliye ve para politikası aktarımı", summary: "Kamu harcaması/vergi ile merkez bankası araçlarının toplam talep ve ekonomi üzerindeki aktarım kanallarını ayırır.", takeaways: ["Maliye politikası kamu bütçesi araçlarını kullanır.", "Para politikası finansal koşulları ve toplam talebi etkiler.", "Politikanın etkisi gecikme, beklenti ve ekonomik koşullara bağlıdır."], checklist: ["Aracı, ara hedefi ve nihai hedefi ayır.", "Genişletici ve daraltıcı yönü belirt.", "Kısa dönem ile uzun dönem sonuçlarını karıştırma."], tags: ["maliye politikası", "para politikası", "toplam talep"], sourceKeys: ["openstaxEconomics"], readingMinutes: 9, level: "Orta" }),
  note({ id: "yonetim-fonksiyonlari", courseCodes: ["İŞL 101"], category: "İşletme", title: "Yönetimin dört işlevi", summary: "Planlama, örgütleme, liderlik ve kontrolü birbirini besleyen yönetim döngüsü olarak açıklar.", takeaways: ["Planlama hedefi ve izlenecek yolu belirler.", "Örgütleme kaynakları, rolleri ve koordinasyonu yapılandırır.", "Kontrol sonuçları ölçer ve düzeltici geri besleme üretir."], checklist: ["Her hedef için sorumlu ve ölçüt belirle.", "Yetki ile hesap verebilirliği eşleştir.", "Kontrol sonucunu yeni plana geri bağla."], tags: ["yönetim", "planlama", "kontrol"], sourceKeys: ["openstaxManagement"], readingMinutes: 7, level: "Başlangıç" }),
  note({ id: "planlama-sureci", courseCodes: ["İŞL 101"], category: "İşletme", title: "Amaçtan eyleme planlama süreci", summary: "Durum analizi, hedef, seçenek, uygulama ve izleme adımlarını karar kalitesini artıracak sırada kurar.", takeaways: ["İyi hedef açık, ölçülebilir ve zamanla sınırlıdır.", "Alternatifler ölçütler belirlenmeden sağlıklı karşılaştırılamaz.", "Plan, izleme ve uyarlama mekanizması içermelidir."], checklist: ["Mevcut durum ile hedef arasındaki farkı yaz.", "En az iki gerçek alternatif üret.", "Erken uyarı göstergesi ve gözden geçirme tarihi koy."], tags: ["planlama", "hedef", "karar"], sourceKeys: ["openstaxPlanning", "openstaxManagement"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "muhasebe-dongusu", courseCodes: ["MUH 101"], category: "Muhasebe", title: "Muhasebe döngüsü ve çift taraflı kayıt", summary: "İşlem analizinden yevmiye, büyük defter, mizan ve finansal tablolara giden akışı özetler.", takeaways: ["Her işlem en az iki hesabı etkiler ve borç-alacak dengesi korunur.", "Borç ve alacak artış/azalış değil hesabın tarafıdır.", "Düzeltme kayıtları dönemsellik ve tahakkuk için gereklidir."], checklist: ["İşlemin ekonomik etkisini önce cümleyle yaz.", "Hesap türüne göre normal bakiyeyi kontrol et.", "Mizan eşitliğinin tek başına hatasızlık kanıtı olmadığını unutma."], tags: ["muhasebe", "yevmiye", "mizan"], sourceKeys: ["openstaxAccounting"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "finansal-tablolar", courseCodes: ["MUH 101"], category: "Muhasebe", title: "Finansal tablolar arasındaki bağ", summary: "Gelir tablosu, özkaynak değişim tablosu, bilanço ve nakit akışını aynı dönem hikâyesinde birleştirir.", takeaways: ["Gelir tablosu dönem performansını gösterir.", "Bilanço belirli tarihte varlık, borç ve özkaynağı sunar.", "Kâr ile nakit aynı şey değildir."], checklist: ["Dönem ve tarih ifadelerini ayır.", "Net kârın özkaynağa aktarımını takip et.", "Nakit hareketini faaliyet, yatırım ve finansman olarak sınıflandır."], tags: ["bilanço", "gelir tablosu", "nakit akışı"], sourceKeys: ["openstaxAccounting"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "ic-kontrol", courseCodes: ["MUH 101", "İŞL 101"], category: "Muhasebe", title: "İç kontrol: hata ve hile riskini azaltma", summary: "Görevlerin ayrılığı, yetkilendirme, belge, fiziksel kontrol ve mutabakat ilkelerini örnekler.", takeaways: ["İç kontrol makul güvence sağlar; mutlak güvence sağlamaz.", "Yetkilendirme, kayıt ve varlık saklama görevleri ayrılmalıdır.", "Bağımsız mutabakat hatayı daha erken görünür kılar."], checklist: ["Tek kişinin uçtan uca kontrol ettiği süreçleri bul.", "Kritik işlemler için onay izi oluştur.", "Kontrolün maliyetini ve önlediği riski birlikte değerlendir."], tags: ["iç kontrol", "risk", "muhasebe"], sourceKeys: ["openstaxControls"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "stp", courseCodes: ["PAZ 201"], category: "Pazarlama", title: "STP: bölümleme, hedefleme ve konumlandırma", summary: "Pazarı anlamlı gruplara ayırıp uygun hedefi seçme ve net değer önerisi kurma süreci.", takeaways: ["Bölümleme benzer ihtiyaç ya da davranış gösteren grupları tanımlar.", "Hedefleme her segmentin çekiciliğini ve işletme uyumunu değerlendirir.", "Konumlandırma müşterinin zihninde rakiplere göre anlamlı bir yer kurar."], checklist: ["Segmentin ölçülebilir ve erişilebilir olduğunu doğrula.", "Hedef seçim ölçütlerini açıkça yaz.", "Konumlandırmayı hedef, kategori, fark ve kanıtla ifade et."], tags: ["stp", "segmentasyon", "konumlandırma"], sourceKeys: ["openstaxMarketing", "openstaxPositioning"], readingMinutes: 8, level: "Başlangıç", featured: true }),
  note({ id: "pazarlama-karmasi", courseCodes: ["PAZ 201"], category: "Pazarlama", title: "Pazarlama karması: tutarlı 4P kararları", summary: "Ürün, fiyat, dağıtım ve tutundurma kararlarını hedef müşteri ve konumlandırmayla aynı çizgide kurar.", takeaways: ["4P birbirinden bağımsız taktikler değil, birlikte çalışan bir sistemdir.", "Fiyat değer algısını ve talebi aynı anda etkiler.", "Dağıtım müşterinin ürüne erişimini tasarlar."], checklist: ["Her P kararını hedef segmentle ilişkilendir.", "Birbiriyle çelişen sinyalleri ara.", "Sonucu müşteri ve işletme ölçütleriyle izle."], tags: ["4p", "ürün", "fiyat"], sourceKeys: ["openstaxMarketing"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "uluslararasi-ticaret-sistemi", courseCodes: ["UTL 101"], category: "Ticaret ve Lojistik", title: "Uluslararası ticaret sisteminin temel çerçevesi", summary: "Ticaretin karşılaştırmalı üstünlük mantığını ve WTO sistemindeki temel ilke başlıklarını ayırır.", takeaways: ["Karşılaştırmalı üstünlük fırsat maliyetleri üzerinden uzmanlaşmayı açıklar.", "Tarife sınırda alınan bir vergi, kota miktar kısıtıdır.", "Çok taraflı ticaret kuralları öngörülebilirlik ve ayrımcılık yapmama ilkeleri etrafında kurulur."], checklist: ["Mutlak ve karşılaştırmalı üstünlüğü karıştırma.", "Politika aracının fiyat, miktar ve refah etkilerini ayrı incele.", "Güncel kural için WTO ve resmi mevzuatı yeniden kontrol et."], tags: ["uluslararası ticaret", "wto", "tarife"], sourceKeys: ["wtoTrade", "openstaxEconomics"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "eoq", courseCodes: ["UTL 201"], category: "Ticaret ve Lojistik", title: "EOQ: sipariş ve stok maliyeti dengesi", summary: "Ekonomik sipariş miktarı modelinin mantığını, varsayımlarını ve uygulama sınırlarını açıklar.", takeaways: ["EOQ sipariş verme ve elde bulundurma maliyetlerini dengeler.", "Klasik model talep ve teslim süresini sabit varsayar.", "Miktar indirimi veya kapasite kısıtı varsa temel sonuç doğrudan kullanılamaz."], checklist: ["Talep, sipariş ve elde bulundurma maliyeti birimlerini eşleştir.", "Model varsayımlarını veriyle karşılaştır.", "Sonucu uygulanabilir sipariş miktarına göre duyarlılık testine sok."], tags: ["eoq", "stok", "sipariş"], sourceKeys: ["mitLogistics"], readingMinutes: 9, level: "Orta" }),
  note({ id: "emniyet-stoku", courseCodes: ["UTL 201"], category: "Ticaret ve Lojistik", title: "Emniyet stoku ve yeniden sipariş noktası", summary: "Talep ve teslim süresi belirsizliğinde hizmet seviyesi ile stok maliyeti arasındaki dengeyi kurar.", takeaways: ["Yeniden sipariş noktası teslim süresi talebi ile emniyet stokunu birleştirir.", "Belirsizlik arttıkça aynı hizmet seviyesi için daha fazla tampon gerekir.", "Hizmet seviyesi tanımı seçilen ölçüte göre değişir."], checklist: ["Talep ve teslim süresini aynı zaman birimine getir.", "Belirsizliğin hangi kaynaktan geldiğini belirle.", "Stok yokluğu maliyetiyle taşıma maliyetini birlikte izle."], tags: ["emniyet stoku", "hizmet seviyesi", "yeniden sipariş"], sourceKeys: ["mitLogistics"], readingMinutes: 9, level: "Orta" }),
  note({ id: "tahmin-risk-pooling", courseCodes: ["UTL 201"], category: "Ticaret ve Lojistik", title: "Talep tahmini ve risk havuzlama", summary: "Tahmin hatasını izleme ve talebi toplulaştırmanın değişkenlik üzerindeki etkisini açıklar.", takeaways: ["Tahmin tek sayı değil, hata dağılımıyla birlikte değerlendirilmelidir.", "Toplulaştırma bağımsız değişkenlikleri kısmen dengeleyebilir.", "Geçmiş örüntü yapısal değişim olduğunda tek başına yeterli değildir."], checklist: ["Eğilim, mevsimsellik ve aykırı değerleri ayır.", "MAE gibi ölçeğe bağlı ve yüzde ölçülerini amaca göre seç.", "Tahmini düzenli olarak gerçekleşen sonuçla geri test et."], tags: ["tahmin", "risk pooling", "tedarik zinciri"], sourceKeys: ["mitLogistics", "mitSupply"], readingMinutes: 9, level: "Orta" }),
  note({ id: "hukuki-kaynak-okuma", courseCodes: ["HUK 101", "SBKY 101"], category: "Hukuk ve Siyaset", title: "Hukuki kaynağı doğru okuma", summary: "Mevzuat, yargı kararı ve öğretinin rolünü ayırıp güncel resmi metne ulaşma kontrol listesi sunar.", takeaways: ["Bir hukuk sorusunda kaynak türü ve norm düzeyi belirlenmelidir.", "Madde metni bağlamı, tanımlar ve ilgili hükümlerle birlikte okunur.", "Özet veya ders notu güncel resmi metnin yerine geçmez."], checklist: ["Mevzuat numarası ve yürürlük durumunu doğrula.", "Kavramları Adalet Bakanlığı sözlüğü ve metin içi tanımlarla kontrol et.", "Somut olay için yetkin hukuk danışmanına başvurulması gerekebileceğini belirt."], tags: ["hukuk", "mevzuat", "kaynak"], sourceKeys: ["justiceDictionary", "constitution"], readingMinutes: 8, level: "Başlangıç", featured: true }),
  note({ id: "anayasa-normlar", courseCodes: ["ANA 101", "HUK 101"], category: "Hukuk ve Siyaset", title: "Anayasa, devlet organları ve normlar hiyerarşisi", summary: "Anayasal düzenin temel organlarını ve alt normların üst normlara uygunluğu fikrini çalışma haritasına dönüştürür.", takeaways: ["Anayasa devletin temel kuruluşunu ve temel hak çerçevesini düzenler.", "Yasama, yürütme ve yargı işlevleri anayasal yetki kuralları içinde incelenir.", "Bir hükmü yorumlarken güncel anayasa metni ve ilgili değişiklikler esas alınır."], checklist: ["İlgili anayasa maddesini resmi metinden aç.", "Yetki, usul ve denetim başlıklarını ayrı incele.", "Ders notundaki tarihsel bilgiyi güncel metinle karıştırma."], tags: ["anayasa", "devlet organları", "normlar"], sourceKeys: ["constitution"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "temel-hak-inceleme", courseCodes: ["ANA 101", "SBKY 101"], category: "Hukuk ve Siyaset", title: "Temel hak sorusu çözme şeması", summary: "Hak alanı, müdahale, kanuni dayanak, meşru amaç ve ölçülülük basamaklarıyla düzenli inceleme yapar.", takeaways: ["Önce olayın hangi hak alanına girdiği belirlenir.", "Bir sınırlama kanuni dayanak ve anayasal güvence çerçevesinde incelenir.", "Ölçülülük elverişlilik, gereklilik ve orantılılık değerlendirmesini içerir."], checklist: ["Hak sahibi, müdahale eden makam ve eylemi yaz.", "İlgili anayasa maddesinin tamamını oku.", "Olayın güncel içtihat gerektirip gerektirmediğini belirt."], tags: ["temel haklar", "ölçülülük", "anayasa"], sourceKeys: ["constitution"], readingMinutes: 9, level: "Orta" }),
  note({ id: "medeni-hukuk-sistematik", courseCodes: ["MED 101"], category: "Hukuk ve Siyaset", title: "Medeni hukukun sistematiği", summary: "Kişiler, aile, miras ve eşya hukuku bölümlerini somut olayda doğru kapıyı bulmak için haritalar.", takeaways: ["Medeni Kanun başlangıç hükümleriyle birlikte bütün olarak okunur.", "Hak ehliyeti ile fiil ehliyeti farklı kavramlardır.", "Dürüstlük kuralı ve hakkın kötüye kullanılması yasağı birçok özel ilişkiyi etkiler."], checklist: ["Kişiyi, hukuki ilişkiyi ve hakkın türünü belirle.", "Genel hüküm ile özel hüküm ilişkisini kontrol et.", "Maddeyi güncel resmi metinden doğrula."], tags: ["medeni hukuk", "ehliyet", "dürüstlük"], sourceKeys: ["civilCode", "justiceDictionary"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "borclar-sozlesme", courseCodes: ["HUK 101", "MED 101"], category: "Hukuk ve Siyaset", title: "Sözleşmenin kurulması ve borcun ifası", summary: "İrade açıklamaları, sözleşmenin içeriği, ifa ve ihlal başlıklarını resmi kanun metni üzerinden çalışma sırasına koyar.", takeaways: ["Sözleşmenin kurulması karşılıklı ve uygun irade açıklamalarını gerektirir.", "Borcun konusu, ifa zamanı ve yeri uyuşmazlık analizini etkiler.", "Temerrüt, imkânsızlık ve gereği gibi ifa etmeme farklı sonuçlara bağlanabilir."], checklist: ["Tarafları ve her bir borcu ayrı yaz.", "Özel şekil veya geçerlilik şartı olup olmadığını kontrol et.", "Uygulanacak güncel madde ve özel düzenlemeleri doğrula."], tags: ["borçlar", "sözleşme", "ifa"], sourceKeys: ["obligationsCode", "justiceDictionary"], readingMinutes: 10, level: "Orta" }),
  note({ id: "roma-sistematik", courseCodes: ["ROM 101"], category: "Hukuk ve Siyaset", title: "Roma özel hukukunun çalışma haritası", summary: "Kaynaklar, kişiler, eşya, borçlar, miras ve usul başlıklarını modern özel hukukla karşılaştırmalı çalışmak için düzenler.", takeaways: ["Roma hukuku tarihsel dönem ve kaynaklarıyla birlikte değerlendirilir.", "Kişiler, eşya ve davalar ayrımı hukuk sistematiği üzerinde kalıcı etki bırakmıştır.", "Mülkiyet, zilyetlik ve borç ilişkisi birbirinden ayrı hukuki yapılardır."], checklist: ["Kavramın Latince adını ve Türkçe karşılığını eşleştir.", "Tarihsel kurum ile bugünkü kuralı özdeş sayma.", "Her kurum için hak, taraf ve dava yolunu ayrı yaz."], tags: ["roma hukuku", "personae", "res"], sourceKeys: ["ankaraRoman", "romaTreRoman"], readingMinutes: 10, level: "Başlangıç" }),
  note({ id: "roma-borclar", courseCodes: ["ROM 101"], category: "Hukuk ve Siyaset", title: "Roma hukukunda borç ve sözleşme sınıfları", summary: "Borç kaynağı, edim ve sözleşme türlerini modern borçlar hukukunun tarihsel arka planıyla birlikte konumlandırır.", takeaways: ["Obligatio alacaklı ile borçlu arasında hukuki bağ kurar.", "Roma sözleşme sistemi şekli ve kuruluş tarzına göre farklı türler tanır.", "Sözleşme ve haksız fiil borcun farklı kaynakları olarak incelenir."], checklist: ["Borcu doğuran olayı sınıflandır.", "Sözleşmenin kuruluş unsurunu belirt.", "Modern hukukla benzerlik kadar ayrılığı da yaz."], tags: ["roma hukuku", "obligatio", "contractus"], sourceKeys: ["ankaraRoman", "romaTreRoman"], readingMinutes: 10, level: "Orta" }),
  note({ id: "siyaset-temel-kavramlar", courseCodes: ["SBKY 101"], category: "Hukuk ve Siyaset", title: "Siyaset biliminin temel kavramları", summary: "İktidar, otorite, meşruiyet, devlet, rejim ve siyasal katılım kavramlarını birbirinden ayırır.", takeaways: ["İktidar davranışı etkileyebilme kapasitesidir.", "Meşruiyet yönetme hakkının kabul edilmesiyle ilgilidir.", "Devlet, hükümet ve rejim aynı kavram değildir."], checklist: ["Kavramı tanımlayıp bir karşı örnek ver.", "Kurum ile onu geçici olarak yöneten aktörü ayır.", "Normatif yargı ile ampirik açıklamayı karıştırma."], tags: ["siyaset", "iktidar", "meşruiyet"], sourceKeys: ["ankaraPolitics"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "turk-siyasal-hayat-zaman-cizgisi", courseCodes: ["SBKY 201"], category: "Hukuk ve Siyaset", title: "Türk siyasal hayatını dönemlere ayırma", summary: "Cumhuriyet dönemi siyasal gelişmeleri parti sistemi, seçimler, anayasal düzen ve kesintiler ekseninde kronolojik çalıştırır.", takeaways: ["Dönemlendirme tek bir olay yerine kurum, seçim ve anayasa değişimlerini birlikte izlemelidir.", "1940'ların ikinci yarısı çok partili siyasal yaşama kalıcı geçiş açısından temel bir eşiktir.", "1980 sonrası siyasal düzen 1982 Anayasası ve yeni parti sistemi bağlamında incelenir."], checklist: ["Her dönem için anayasal çerçeveyi yaz.", "Seçim, parti ve hükümet değişimini ayrı sütunlarda izle.", "Tartışmalı yorumları TBMM yayını ve akademik kaynakla karşılaştır."], tags: ["türk siyasal hayatı", "çok partili hayat", "seçimler"], sourceKeys: ["tbmmHistory", "constitution"], readingMinutes: 11, level: "Orta" }),
  note({ id: "psikoloji-bilimsel-yontem", courseCodes: ["PSK 101", "PDR 101"], category: "Psikoloji ve Eğitim", title: "Psikolojide bilimsel yöntem", summary: "Betimsel, korelasyonel ve deneysel araştırmayı; değişken, örneklem ve etik açısından karşılaştırır.", takeaways: ["Korelasyon tek başına nedensellik göstermez.", "Deneyde bağımsız değişken araştırmacı tarafından değiştirilir.", "Örneklem seçimi bulguların genellenebilirliğini etkiler."], checklist: ["Araştırma sorusunu ölçülebilir değişkenlere çevir.", "Karıştırıcı değişkenleri belirle.", "Etik onam ve katılımcı güvenliğini değerlendir."], tags: ["psikoloji", "araştırma", "korelasyon"], sourceKeys: ["openstaxPsychology"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "ogrenme-kosullanma", courseCodes: ["PSK 101", "EĞT 101", "SNO 101"], category: "Psikoloji ve Eğitim", title: "Klasik ve edimsel koşullanma", summary: "Uyaranlar arası öğrenme ile davranış-sonuç ilişkisini, pekiştirme ve ceza kavramlarını ayırarak açıklar.", takeaways: ["Klasik koşullanma iki uyaran arasındaki ilişkiyi öğrenir.", "Edimsel koşullanma davranışın sonuçlarla değişmesini inceler.", "Pekiştirme davranışı artırır; ceza azaltmayı amaçlar."], checklist: ["Olumlu/olumsuz sözcüğünü ekleme/çıkarma olarak yorumla.", "Davranışın artıp azaldığını kontrol et.", "Uyaran, tepki ve sonucu ayrı işaretle."], tags: ["öğrenme", "koşullanma", "pekiştirme"], sourceKeys: ["openstaxPsychology"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "bellek-sistemleri", courseCodes: ["PSK 101", "PDR 201", "SNO 101"], category: "Psikoloji ve Eğitim", title: "Bellek sistemleri ve unutma", summary: "Kodlama, depolama ve geri getirmeyi; çalışma belleği ile uzun süreli belleğin görevlerini birlikte açıklar.", takeaways: ["Bellek pasif kayıt değil, kodlama ve yeniden yapılandırma sürecidir.", "Çalışma belleğinin kapasitesi sınırlıdır.", "Geri getirme ipuçları hatırlamayı güçlü biçimde etkiler."], checklist: ["Bilgiyi anlamlı kümelere ayır.", "Okumak yerine kendini sınayarak geri getir.", "Çalışmayı günlere yay ve aralıklı tekrar yap."], tags: ["bellek", "unutma", "geri getirme"], sourceKeys: ["openstaxPsychology", "openstaxMemory"], readingMinutes: 8, level: "Başlangıç", featured: true }),
  note({ id: "yasam-boyu-gelisim", courseCodes: ["PDR 201", "PSK 101"], category: "Psikoloji ve Eğitim", title: "Yaşam boyu gelişim: alanlar ve dönemler", summary: "Fiziksel, bilişsel ve sosyo-duygusal gelişimi doğum öncesinden ileri yetişkinliğe kadar çok boyutlu okur.", takeaways: ["Gelişim yaşam boyu sürer ve birden çok alanda gerçekleşir.", "Biyolojik, psikolojik ve bağlamsal etkenler birlikte çalışır.", "Yaş dönemleri ortalama örüntülerdir; bireysel farklılığı ortadan kaldırmaz."], checklist: ["İncelenen gelişim alanını belirt.", "Yaş ile nedenselliği özdeşleştirme.", "Kültür, aile ve çevre bağlamını ekle."], tags: ["gelişim", "yaşam boyu", "bilişsel"], sourceKeys: ["openstaxLifespan"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "pdr-sureci", courseCodes: ["PDR 101"], category: "Psikoloji ve Eğitim", title: "PDR alanı ve yardım sürecinin sınırları", summary: "Rehberlik, psikolojik danışma, önleme ve yönlendirme işlevlerini rol ve etik sınırlar üzerinden konumlandırır.", takeaways: ["PDR hizmeti gelişimsel, önleyici ve iyileştirici işlevler içerebilir.", "Gizlilik temel ilkedir ancak yasal ve güvenlik istisnaları olabilir.", "Uzmanlık sınırını aşan ihtiyaçlarda uygun kuruma yönlendirme gerekir."], checklist: ["Rol, amaç ve hizmet düzeyini açıkla.", "Bilgilendirilmiş onam ve gizlilik sınırlarını belirt.", "Acil riskte kurumun güncel protokolünü izle."], tags: ["pdr", "etik", "gizlilik"], sourceKeys: ["ankaraPdr"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "egitim-bilimleri-harita", courseCodes: ["EĞT 101", "İMA 101"], category: "Psikoloji ve Eğitim", title: "Eğitim bilimlerinin çalışma haritası", summary: "Amaç, program, öğretim, öğrenme, ölçme ve rehberlik bileşenlerini tek eğitim sistemi içinde ilişkilendirir.", takeaways: ["Eğitim hedefi, öğretim etkinliği ve değerlendirme birbiriyle uyumlu olmalıdır.", "Öğrenme kanıtı yalnız anlatımın tamamlanması değildir.", "Öğrenci özellikleri ve bağlam öğretim kararını etkiler."], checklist: ["Hedefi gözlenebilir öğrenme çıktısı olarak yaz.", "Etkinliği hedefle doğrudan eşleştir.", "Değerlendirmenin gerçekten hedefi ölçtüğünü kontrol et."], tags: ["eğitim", "öğretim", "ölçme"], sourceKeys: ["apaRetrieval", "openstaxPsychology"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "geri-getirme-pratigi", courseCodes: ["EĞT 101", "SNO 101", "İMA 101", "PDR 101"], category: "Psikoloji ve Eğitim", title: "Etkili çalışma: geri getirme ve aralıklı tekrar", summary: "Tekrar okumak yerine bilgiyi bellekten çağırma ve çalışmayı zamana yayma üzerine kanıta dayalı plan.", takeaways: ["Kendini sınama, öğrenilen bilgiyi geri getirme pratiği sağlar.", "Aralıklı çalışma aynı sürenin tek oturumda toplanmasından daha kalıcı olabilir.", "Hata sonrası doğru geri bildirim öğrenmenin parçasıdır."], checklist: ["Notu kapatıp ana fikirleri yaz.", "Soruları günlere yayılan takvime yerleştir.", "Yanlış cevaplar için neden yanlış günlüğü tut."], tags: ["çalışma", "retrieval practice", "aralıklı tekrar"], sourceKeys: ["apaRetrieval", "openstaxMemory"], readingMinutes: 7, level: "Başlangıç" }),
  note({ id: "matematik-ogretimi-temsil", courseCodes: ["İMA 101", "SNO 101"], category: "Psikoloji ve Eğitim", title: "Matematik öğretiminde temsil ve kavram", summary: "Sözel, sembolik, görsel ve somut temsiller arasında geçişi kavramsal öğrenmenin aracı olarak kullanır.", takeaways: ["Bir gösterimi kullanmak kavramı tek başına anlamak değildir.", "Temsil dönüşümü öğrencinin ilişkileri görünür kılmasını sağlar.", "Örnek ve örnek olmayan durumlar kavram sınırını netleştirir."], checklist: ["Aynı fikri en az iki temsille göster.", "Öğrenciden temsiller arası açıklama iste.", "Sık kavram yanılgısı için karşı örnek hazırla."], tags: ["matematik öğretimi", "temsil", "kavram"], sourceKeys: ["mitMathCs", "apaRetrieval"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "turkce-yazim", courseCodes: ["TÜR 101", "EDB 101"], category: "Türk Dili ve Edebiyatı", title: "Yazım kontrolü: resmi kılavuzla çalışma", summary: "Birleşik kelimeler, büyük harfler, sayıların yazımı ve sık karıştırılan biçimleri TDK kaynağından doğrulama yöntemi.", takeaways: ["Yazım kararı sezgiyle değil güncel kılavuz ve sözlükle doğrulanır.", "Özel adlara gelen eklerde kesme kullanımı sözcük türüne göre değişir.", "Birleşik kelimelerin yazımı tek bir ses kuralına indirgenemez."], checklist: ["Şüpheli sözcüğü TDK Yazım Kılavuzu'nda ara.", "Özel ad, kurum adı ve kısaltmayı ayrı değerlendir.", "Metin boyunca aynı biçimi tutarlı kullan."], tags: ["yazım", "tdk", "türk dili"], sourceKeys: ["tdkSpelling"], readingMinutes: 8, level: "Başlangıç", featured: true }),
  note({ id: "noktalama-anlam", courseCodes: ["TÜR 101", "EDB 101"], category: "Türk Dili ve Edebiyatı", title: "Noktalama işaretleri ve anlam akışı", summary: "Noktalamayı nefes işareti olarak değil cümle yapısı, ilişki ve alıntı düzeninin göstergesi olarak ele alır.", takeaways: ["Virgül özne ile yüklemi keyfî biçimde ayırmaz.", "Noktalı virgül ilişkili fakat iç yapısı virgüllü grupları ayırabilir.", "Doğrudan alıntı ve aktarma cümlesi farklı noktalama düzenleri gerektirir."], checklist: ["Önce cümlenin ögelerini ve sınırlarını belirle.", "İşaretin TDK'daki işlevini örnekle karşılaştır.", "Alıntı işaretleri ve kaynak gösterimini birlikte kontrol et."], tags: ["noktalama", "cümle", "anlatım"], sourceKeys: ["tdkPunctuation"], readingMinutes: 8, level: "Başlangıç" }),
  note({ id: "turkce-dilbilgisi", courseCodes: ["TÜR 101"], category: "Türk Dili ve Edebiyatı", title: "Sözcükten cümleye dil bilgisi haritası", summary: "Kök-ek, sözcük türü, öbek, öge ve cümle düzeylerini birbirine karıştırmadan çözümleme sırasına koyar.", takeaways: ["Biçim bilgisi sözcük yapısını, söz dizimi sözcükler arası ilişkiyi inceler.", "Aynı sözcük bağlama göre farklı tür veya görev üstlenebilir.", "Cümle ögesi bulunurken yüklem ve anlam ilişkisi birlikte kullanılır."], checklist: ["Önce çekimli yüklemi belirle.", "Ekleri yapım ve çekim olarak ayır.", "Sözcük türünü yalnız biçime değil cümledeki işleve göre doğrula."], tags: ["dil bilgisi", "biçim bilgisi", "söz dizimi"], sourceKeys: ["ankaraGrammar", "tdkSpelling"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "edebi-metin-inceleme", courseCodes: ["EDB 101"], category: "Türk Dili ve Edebiyatı", title: "Edebî metin inceleme iskeleti", summary: "Tür, anlatıcı, bakış açısı, zaman, mekân, kişi, tema ve dil kullanımını kanıta dayalı yorum sırasına yerleştirir.", takeaways: ["Tema metnin tek cümlelik özeti değil, işlenen temel düşünce alanıdır.", "Anlatıcı yazarla otomatik olarak özdeş değildir.", "Yorum metinden alıntı ya da açık göstergeyle desteklenmelidir."], checklist: ["Tür ve anlatım durumunu belirle.", "İddia, metin kanıtı ve yorum üçlüsünü kur.", "Biçimsel tercihin anlama etkisini açıkla."], tags: ["edebiyat", "metin inceleme", "anlatıcı"], sourceKeys: ["ankaraStoryAnalysis"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "cocuk-edebiyati", courseCodes: ["TÜR 201", "SNO 101"], category: "Türk Dili ve Edebiyatı", title: "Çocuk edebiyatında nitelik ölçütleri", summary: "Metni yaşa uygunluk, çocuğa görelik, dil, görsel tasarım, tema ve kalıp yargılar açısından değerlendirme rehberi.", takeaways: ["Çocuğa görelik metni basitleştirmekten daha geniş bir ölçüttür.", "Dil, içerik ve görsel tasarım gelişim düzeyiyle birlikte değerlendirilir.", "Didaktik amaç edebî niteliğin yerini tek başına tutmaz."], checklist: ["Hedef yaş ve okuma deneyimini belirt.", "Dil, tema ve görsel unsurlar için somut kanıt topla.", "Kalıp yargı, dışlama ve korku öğelerini bağlamıyla incele."], tags: ["çocuk edebiyatı", "çocuğa görelik", "metin seçimi"], sourceKeys: ["ankaraChildren"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "hucre-organeller", courseCodes: ["TIP 101", "TIP 201"], category: "Temel Tıp Bilimleri", title: "Hücre yapısı ve organel iş bölümü", summary: "Hücre zarı, çekirdek, ribozom, endoplazmik retikulum, Golgi, lizozom ve mitokondriyi işlev akışı içinde bağlar.", takeaways: ["Hücre zarı seçici geçirgen bir sınır ve iletişim yüzeyidir.", "Protein sentezi ribozomda, işlenme ve yönlendirme ER-Golgi hattında gerçekleşir.", "Mitokondri enerji dönüşümünde merkezi rol oynar ancak tek ATP kaynağı değildir."], checklist: ["Her organeli yapı, işlev ve klinik sonuçla eşleştir.", "Prokaryot ve ökaryot farklarını ayrı yaz.", "Bir salgı proteininin hücre içi yolunu sırayla çiz."], tags: ["hücre", "organel", "protein"], sourceKeys: ["openstaxCells", "openstaxBiology"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "hucre-zari-tasima", courseCodes: ["TIP 101", "TIP 103"], category: "Temel Tıp Bilimleri", title: "Hücre zarından madde taşınması", summary: "Basit difüzyon, kolaylaştırılmış difüzyon, ozmoz, aktif taşıma ve veziküler taşımayı enerji ve gradyan açısından ayırır.", takeaways: ["Pasif taşıma elektrokimyasal gradyan yönünde enerji harcamadan ilerler.", "Aktif taşıma gradyana karşı hareket için doğrudan ya da dolaylı enerji kullanır.", "Ozmoz suyun seçici geçirgen zar boyunca hareketidir."], checklist: ["Taşınan maddeyi, zarı ve gradyanı tanımla.", "Taşıyıcı veya kanal gerekip gerekmediğini belirt.", "Tonisite ile ozmolariteyi özdeş sayma."], tags: ["zar", "difüzyon", "aktif taşıma"], sourceKeys: ["openstaxBiology", "openstaxAnatomy"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "genetik-bilgi-akisi", courseCodes: ["TIP 101", "TIP 201"], category: "Temel Tıp Bilimleri", title: "DNA'dan proteine bilgi akışı", summary: "Replikasyon, transkripsiyon, RNA işlenmesi ve translasyonu aynı gen ifadesi zincirinde konumlandırır.", takeaways: ["Replikasyon DNA'nın, transkripsiyon RNA'nın sentezidir.", "Genetik kod kodonlar halinde okunur ve dejeneredir.", "Gen ifadesi farklı düzenleme basamaklarında değiştirilebilir."], checklist: ["Kalıp ve kodlayan zinciri ayır.", "5' ve 3' yönlerini işaretle.", "Mutasyonun RNA ve protein düzeyindeki olası etkisini sırayla izle."], tags: ["dna", "rna", "protein sentezi"], sourceKeys: ["openstaxBiology"], readingMinutes: 10, level: "Orta" }),
  note({ id: "kimya-mol-stokiyometri", courseCodes: ["TIP 101"], category: "Temel Tıp Bilimleri", title: "Mol, denklem denkleştirme ve stokiyometri", summary: "Kimyasal denklemde atom korunumu, mol oranı, sınırlayıcı bileşen ve verim hesabını sistematikleştirir.", takeaways: ["Denkleştirme alt indisleri değil katsayıları değiştirir.", "Denklem katsayıları mol oranlarını verir.", "Sınırlayıcı bileşen oluşabilecek ürün miktarını belirler."], checklist: ["Önce denklemi denkleştir.", "Tüm miktarları mole çevir.", "Birim ve anlamlı basamak kontrolü yap."], tags: ["kimya", "mol", "stokiyometri"], sourceKeys: ["openstaxChemistry"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "kimyasal-baglar", courseCodes: ["TIP 101"], category: "Temel Tıp Bilimleri", title: "Kimyasal bağlar ve moleküler etkileşimler", summary: "İyonik, kovalent ve moleküller arası etkileşimleri elektron paylaşımı, polarite ve biyolojik sonuçlarla bağlar.", takeaways: ["Bağ türü atomlar arasındaki elektron dağılımıyla ilişkilidir.", "Bağ polaritesi ile molekül polaritesi aynı şey değildir.", "Hidrojen bağı kovalent bağdan farklı, yönlü bir moleküller arası etkileşimdir."], checklist: ["Elektronegatiflik ve molekül geometrisini birlikte değerlendir.", "Bağ içi ve moleküller arası kuvveti ayır.", "Suda çözünürlük yorumunu polariteyle gerekçelendir."], tags: ["kimyasal bağ", "polarite", "hidrojen bağı"], sourceKeys: ["openstaxChemistry"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "anatomi-yon-duzlem", courseCodes: ["TIP 102"], category: "Temel Tıp Bilimleri", title: "Anatomik pozisyon, yönler ve düzlemler", summary: "Vücut bölgelerini standart anatomik pozisyona göre tarif etmek için yön ve kesit dilini düzenler.", takeaways: ["Sağ-sol her zaman incelenen kişinin sağı ve soludur.", "Sagittal, frontal ve transvers düzlemler farklı kesit yönlerini tanımlar.", "Proksimal-distal özellikle ekstremitelerde bağlantı noktasına göre kullanılır."], checklist: ["Önce anatomik pozisyonu varsay.", "İki yapı arasındaki ilişkiyi karşılaştırmalı terimle yaz.", "Düzlem ile ekseni karıştırma."], tags: ["anatomi", "düzlem", "yön"], sourceKeys: ["openstaxAnatomy"], readingMinutes: 8, level: "Başlangıç", featured: true }),
  note({ id: "doku-turleri", courseCodes: ["TIP 102", "TIP 201"], category: "Temel Tıp Bilimleri", title: "Dört temel doku türü", summary: "Epitel, bağ, kas ve sinir dokusunu hücre düzeni, matriks ve ana işlevleri üzerinden ayırır.", takeaways: ["Epitel dokusu yüzeyleri örter ve bezleri oluşturur.", "Bağ dokusunda hücre dışı matriks belirgin bir bileşendir.", "Kas dokusu kasılma, sinir dokusu hızlı iletişim için özelleşmiştir."], checklist: ["Hücre yoğunluğu ve matriks miktarını karşılaştır.", "Doku alt tipini işlevle ilişkilendir.", "Mikroskobik görünümden tek belirtiyle karar verme."], tags: ["histoloji", "epitel", "bağ dokusu"], sourceKeys: ["openstaxAnatomy"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "homeostaz", courseCodes: ["TIP 103", "TIP 101"], category: "Temel Tıp Bilimleri", title: "Homeostaz ve geri bildirim döngüleri", summary: "Reseptör, kontrol merkezi ve efektör bileşenleriyle fizyolojik değişkenlerin düzenlenmesini açıklar.", takeaways: ["Homeostaz değişmezlik değil, dinamik bir düzenleme durumudur.", "Negatif geri bildirim sapmayı azaltır.", "Pozitif geri bildirim yanıtı büyütür ve genellikle dış bir sonlandırıcı olay gerektirir."], checklist: ["Düzenlenen değişkeni ve normal aralığı belirt.", "Uyarı, algılayıcı, merkez ve efektörü sırala.", "Yanıtın başlangıç değişikliğini azaltıp artırdığını kontrol et."], tags: ["homeostaz", "geri bildirim", "fizyoloji"], sourceKeys: ["ncbiHomeostasis", "openstaxAnatomy"], readingMinutes: 9, level: "Başlangıç" }),
  note({ id: "aksiyon-potansiyeli", courseCodes: ["TIP 103"], category: "Temel Tıp Bilimleri", title: "Aksiyon potansiyeli adımları", summary: "Dinlenim potansiyelinden depolarizasyon, repolarizasyon ve refrakter döneme uzanan iyon akımlarını sıraya koyar.", takeaways: ["Aksiyon potansiyeli eşik aşıldığında hep-ya-da-hiç biçiminde oluşur.", "Voltaj kapılı sodyum ve potasyum kanalları farklı zamanlarda etkinleşir.", "Refrakter dönem tek yönlü yayılımı ve ateşleme sıklığını etkiler."], checklist: ["Her fazda membran potansiyeli yönünü yaz.", "Açılan ve inaktive olan kanalları ayır.", "İyonun elektrokimyasal itici gücünü dikkate al."], tags: ["aksiyon potansiyeli", "nöron", "iyon kanalı"], sourceKeys: ["openstaxActionPotential"], readingMinutes: 10, level: "Orta" }),
  note({ id: "endokrin-sinyal", courseCodes: ["TIP 103"], category: "Temel Tıp Bilimleri", title: "Endokrin sistem ve hormon sinyali", summary: "Hormon sınıfları, reseptör yerleşimi, hedef hücre özgüllüğü ve geri bildirim kontrolünü karşılaştırır.", takeaways: ["Bir hormon yalnız uygun reseptörü taşıyan hedef hücreleri etkiler.", "Peptit hormonlar çoğunlukla zar reseptörü, steroid hormonlar hücre içi reseptör kullanır.", "Endokrin eksenler sıkça negatif geri bildirimle düzenlenir."], checklist: ["Kaynak bez, hormon ve hedef dokuyu eşleştir.", "Reseptörün hücre içi mi zar üzerinde mi olduğunu belirt.", "Primer bez ve düzenleyici hormon bozukluğunu ayır."], tags: ["endokrin", "hormon", "reseptör"], sourceKeys: ["openstaxEndocrine"], readingMinutes: 9, level: "Orta" }),
  note({ id: "akut-inflamasyon", courseCodes: ["TIP 201"], category: "Temel Tıp Bilimleri", title: "Akut inflamasyonun temel akışı", summary: "Doku hasarından damar değişiklikleri, lökosit göçü ve olası sonlanımlara uzanan patoloji sırasını açıklar.", takeaways: ["Akut inflamasyon hızlı başlayan doğuştan bağışıklık yanıtıdır.", "Vazodilatasyon ve damar geçirgenliği değişiklikleri kızarıklık, ısı ve ödeme katkı sağlar.", "Nötrofiller akut yanıtın erken hücresel bileşenleri arasındadır."], checklist: ["Nedeni, damar yanıtını ve hücresel yanıtı ayır.", "Beş klasik bulguyu mekanizmayla eşleştir.", "Çözülme, apse ve kronikleşme gibi sonlanımları karşılaştır."], tags: ["inflamasyon", "nötrofil", "patoloji"], sourceKeys: ["ncbiInflammation"], readingMinutes: 10, level: "Orta" }),
  note({ id: "kronik-inflamasyon", courseCodes: ["TIP 201"], category: "Temel Tıp Bilimleri", title: "Kronik inflamasyon ve doku onarımı", summary: "Uzamış uyaranlarda makrofaj-lenfosit ağırlıklı yanıtı, doku hasarı ve fibrozisle birlikte inceler.", takeaways: ["Kronik inflamasyon uzamış bağışıklık yanıtı, doku hasarı ve onarımı birlikte içerebilir.", "Makrofajlar ve lenfositler hücresel örüntüde belirgindir.", "Süregelen onarım fibrozis ve organ işlev kaybına katkıda bulunabilir."], checklist: ["Akut ve kronik hücresel örüntüyü karşılaştır.", "Süregelen nedeni ve bağışıklık yanıtını ayır.", "Doku hasarı ile onarımın eş zamanlı olabileceğini göster."], tags: ["kronik inflamasyon", "makrofaj", "fibrozis"], sourceKeys: ["ncbiInflammation"], readingMinutes: 10, level: "Orta" }),
];

export const featuredCuratedNotes = curatedNotes.filter((item) => item.featured);

export function getCuratedSources(noteItem: CuratedNote) {
  return noteItem.sourceKeys.map((key) => ({ key, ...curatedSources[key] }));
}
