/**
 * F00 synthetic measurement data. Pure generation only: no network, filesystem,
 * credentials, application imports, database writes, or current-clock reads.
 * These records are not production seed data or registration payloads.
 */
export const FIXTURE_LABEL = "[SYNTHETIC]";
export const FIXTURE_NOW = "2026-09-05T09:00:00.000Z";
export const FIXTURE_SCHEMA_VERSION = 1;

const LONG_NAME = "İlknur Şükran Çağla Öztürk Çalışkan";
const LONG_TEXT = "İstanbul'dan Şırnak'a uzanan öğrenci çalışma grubumuz; ölçme, değerlendirme, erişilebilirlik ve çok dilli iletişim üzerine notlarını karşılaştırıyor. İı, Iı, Şş, Ğğ, Üü, Öö ve Çç karakterleri kırpılmadan görünmeli.";
const UNBROKEN_TEXT = "ÇığÖğrenciİletişimi".repeat(12);

function count(value, name) {
  if (!Number.isSafeInteger(value) || value < 0 || value > 5000) {
    throw new RangeError(`${name} must be an integer from 0 to 5000.`);
  }
  return value;
}

function measurementImage(id, width, height, ratio) {
  // Deliberately a labelled test pattern, not an illustration or a photograph.
  const fontSize = Math.max(5, Math.floor(Math.min(width, height) / 12));
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" fill="#ddd"/><path d="M0 0L${width} ${height}M${width} 0L0 ${height}" stroke="#555" stroke-width="2"/><rect x="1" y="1" width="${width - 2}" height="${height - 2}" fill="none" stroke="#111" stroke-width="2"/><rect y="${height * 0.35}" width="100%" height="${height * 0.3}" fill="#fff"/><text x="50%" y="48%" text-anchor="middle" font-family="sans-serif" font-size="${fontSize}" fill="#111">SYNTHETIC</text><text x="50%" y="60%" text-anchor="middle" font-family="sans-serif" font-size="${fontSize}" fill="#111">${width}x${height} / ${ratio}</text></svg>`;
  return {
    id, kind: "image", width, height, ratio,
    url: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,
    contentType: "image/svg+xml", fileName: `${id}.svg`,
    alt: `${FIXTURE_LABEL} Ölçüm deseni ${width} × ${height}, oran ${ratio}`,
    synthetic: true, measurementOnly: true, availability: "inline-test-pattern",
    provenance: "Procedural measurement pattern generated by Kampira F00; no external media.",
  };
}

/**
 * The seed is a deterministic namespace, not randomness. Defaults generate
 * 200 feed posts and a 100-message conversation, including tied timestamps.
 * SVG images only exercise layout. Videos are honest metadata-only cases.
 */
export function createMobileQualityFixtures({ seed = "f00-v1", postCount = 200, messageCount = 100 } = {}) {
  if (typeof seed !== "string" || !/^[a-z0-9][a-z0-9-]{0,31}$/.test(seed)) {
    throw new TypeError("seed must contain 1–32 lowercase ASCII letters, digits or hyphens, starting with a letter or digit.");
  }
  count(postCount, "postCount");
  count(messageCount, "messageCount");
  const prefix = `synthetic-${seed}`;
  const id = (kind, index) => `${prefix}-${kind}-${String(index).padStart(4, "0")}`;
  const now = Date.parse(FIXTURE_NOW);
  const university = {
    id: `${prefix}-university`, name: `${FIXTURE_LABEL} Uzun İsimli Ölçüm ve Öğrenci Araştırmaları Üniversitesi`,
    shortName: "SYNTHETIC", city: `${FIXTURE_LABEL} Örnek şehir`,
  };
  const department = { id: `${prefix}-department`, name: `${FIXTURE_LABEL} Türkçe Öğretimi ve Disiplinlerarası Eğitim Araştırmaları` };
  const images = [
    ["square", 640, 640, "1:1"], ["portrait", 480, 600, "4:5"],
    ["vertical", 360, 640, "9:16"], ["landscape", 640, 360, "16:9"],
    ["panorama", 960, 240, "4:1"], ["thumbnail", 40, 40, "1:1"],
  ].map(([name, width, height, ratio]) => measurementImage(`${prefix}-${name}`, width, height, ratio));
  const videos = [["vertical-video", 360, 640, "9:16"], ["landscape-video", 640, 360, "16:9"]].map(([name, width, height, ratio]) => ({
    id: `${prefix}-${name}`, kind: "video", width, height, ratio, durationSeconds: 30,
    url: null, contentType: "video/mp4", fileName: `${prefix}-${name}.mp4`,
    posterUrl: measurementImage(`${prefix}-${name}-poster`, width, height, ratio).url,
    alt: `${FIXTURE_LABEL} Video oranı ölçüm tanımı ${ratio}; oynatılabilir dosya yok`,
    synthetic: true, measurementOnly: true, availability: "metadata-only",
    provenance: "No video bytes or external asset; poster is a procedural measurement pattern.",
  }));
  // Existing product assets are optional references, kept out of geometry data.
  // Their presence in the repository does not establish a photographic license.
  const existingProductAssets = [
    ["/social-live/library-study.webp", "image/webp", "Kütüphane ürün varlığı"],
    ["/social-live/campus-event.webp", "image/webp", "Kampüs etkinliği ürün varlığı"],
    ["/social-live/cafeteria.webp", "image/webp", "Kafeterya ürün varlığı"],
    ["/course-covers/study.jpg", "image/jpeg", "Çalışma ders kapağı"],
    ["/course-covers/programming.jpg", "image/jpeg", "Programlama ders kapağı"],
    ["/course-covers/physics.jpg", "image/jpeg", "Fizik ders kapağı"],
    ["/course-covers/mathematics.jpg", "image/jpeg", "Matematik ders kapağı"],
  ].map(([url, contentType, description], index) => ({
    id: id("existing-asset", index + 1), kind: "image", url, contentType,
    fileName: url.split("/").at(-1), alt: `${FIXTURE_LABEL} ${description}`,
    syntheticUsage: true, fixtureLabel: FIXTURE_LABEL, availability: "existing-local-asset",
    provenance: "Existing repository product asset; author and photographic license not verified in F00.",
  }));
  const makeProfile = (key, displayName, empty = false) => ({
    synthetic: true, fixtureState: empty ? "empty" : "populated",
    publicId: `${prefix}-${key}`, email: `${prefix}-${key}@example.invalid`,
    displayName: `${FIXTURE_LABEL} ${displayName}`, handle: `synthetic.${seed}.${key}`,
    universityId: university.id, universityName: university.name, universityShortName: university.shortName,
    departmentId: department.id, departmentName: department.name,
    facultyName: `${FIXTURE_LABEL} Eğitim ve İnsan Bilimleri Fakültesi`, classYear: 2,
    bio: empty ? "" : `${FIXTURE_LABEL} ${LONG_TEXT}`,
    avatarUrl: empty ? null : images[0].url,
    links: empty ? [] : [{ title: `${FIXTURE_LABEL} Test bağlantısı`, url: "https://example.invalid/synthetic-profile" }],
    courses: [], followerIds: [], followingIds: [], postCount: 0,
  });
  const profiles = {
    empty: makeProfile("empty", "Yeni Öğrenci", true),
    populated: makeProfile("active", "Deniz Ölçüm"),
    longName: makeProfile("long", LONG_NAME),
  };
  profiles.populated.followerIds = [profiles.longName.publicId];
  profiles.populated.followingIds = [profiles.longName.publicId];
  profiles.longName.followerIds = [profiles.populated.publicId];
  profiles.longName.followingIds = [profiles.populated.publicId];
  const authors = [profiles.populated, profiles.longName];
  const contentCases = [
    "Kütüphanede birlikte çalışmak isteyen var mı?",
    LONG_TEXT,
    `${LONG_TEXT}\n\n${LONG_TEXT}\n\nSon satır: bağlantı, klavye ve geri dönüş kontrolü.`,
    `${UNBROKEN_TEXT}\nTek sözcük görünümündeki uzun içerik taşma kontrolüdür.`,
    'Metin olarak görünmeli: <script>alert("synthetic")</script> & "tırnak"; 👩🏽‍🎓 📚',
  ];
  const posts = Array.from({ length: postCount }, (_, index) => {
    const author = authors[index % authors.length];
    // Five-post groups put same-author time ties across 12-item API pages.
    const createdAt = new Date(now - Math.floor(index / 5) * 60_000).toISOString();
    return {
      id: id("post", postCount - index), synthetic: true,
      authorId: author.publicId, authorEmail: author.email, name: author.displayName,
      initials: "SY", avatarClass: "avatar-violet", avatarUrl: author.avatarUrl,
      school: university.name, department: department.name,
      audience: index % 3 === 0 ? "campus" : "platform",
      time: `${Math.floor(index / 5)} dk`, createdAt, updatedAt: createdAt, course: "SYNTHETIC",
      text: `${FIXTURE_LABEL} Gönderi ${index + 1}. ${contentCases[index % contentCases.length]}`,
      likes: 0, comments: 0, liked: false, saved: false, edited: false,
      media: index % 4 === 0 ? [{ ...images[Math.floor(index / 4) % images.length], id: id("post-media", index + 1) }] : [],
    };
  });
  for (const profile of Object.values(profiles)) profile.postCount = posts.filter((post) => post.authorId === profile.publicId).length;
  const conversationId = `${prefix}-conversation`;
  const messages = Array.from({ length: messageCount }, (_, index) => {
    const own = index % 2 === 0;
    const createdAt = new Date(now - (Math.ceil(messageCount / 2) - Math.floor(index / 2)) * 60_000).toISOString();
    return {
      id: id("message", index + 1), conversationId, synthetic: true,
      senderId: authors[own ? 0 : 1].publicId, senderEmail: authors[own ? 0 : 1].email,
      createdAt, own, body: `${FIXTURE_LABEL} Mesaj ${index + 1}. ${contentCases[index % contentCases.length]}`,
      attachmentType: null, attachmentId: null, attachment: null,
      read: index < Math.max(0, messageCount - 5), removed: false, time: createdAt.slice(11, 16),
    };
  });
  const lastMessage = messages.at(-1);
  const conversations = lastMessage ? [{
    id: conversationId, synthetic: true, person: { ...profiles.longName },
    preview: lastMessage.body, lastMessageOwn: lastMessage.own,
    unreadCount: messages.filter((message) => !message.own && !message.read).length, time: lastMessage.time,
  }] : [];
  return {
    schemaVersion: FIXTURE_SCHEMA_VERSION, synthetic: true, label: FIXTURE_LABEL,
    seed, now: FIXTURE_NOW, purpose: "Local isolated measurement; never production content",
    university, department, profiles, posts, messages, conversations,
    media: { images, videos, existingProductAssets },
    textCases: { longName: `${FIXTURE_LABEL} ${LONG_NAME}`, longText: `${FIXTURE_LABEL} ${LONG_TEXT}`, unbroken: `${FIXTURE_LABEL} ${UNBROKEN_TEXT}` },
    scenarios: {
      firstUse: { state: "empty", reason: "first-use", profileId: profiles.empty.publicId, posts: [] },
      filteredEmpty: { state: "empty", reason: "no-results", query: `${FIXTURE_LABEL} bulunmayan sorgu`, posts: [] },
      loading: { state: "loading", data: null },
      networkError: { state: "error", status: null, code: "SYNTHETIC_NETWORK_ERROR", message: `${FIXTURE_LABEL} Bağlantı kurulamadı.`, retryable: true, data: null },
      missingSource: { state: "error", status: 404, code: "SYNTHETIC_SOURCE_MISSING", message: `${FIXTURE_LABEL} Kaynak bulunamadı.`, retryable: false, data: null },
      brokenImage: { ...images[0], id: `${prefix}-broken-image`, url: "data:image/png;base64,", contentType: "image/png", fileName: `${prefix}-broken.png`, availability: "intentionally-invalid", alt: `${FIXTURE_LABEL} Bilerek bozuk görsel; hata durumu ölçümü` },
    },
  };
}
